language: node_js
node_js:
-  "6"
before_script:
  - npm install -g bower wintersmith
  - bower install
install:
  - npm install
script:
  - npm run build
after_success:
  - npm run deploy

notifications:
  slack: barcamperfurt:$SLACK_TOKEN