language: node_js
node_js:
- 0.1
before_script:
- npm install -g bower wintersmith
- npm install
- bower install
script:
- git config --global user.email "peter@eyeem.com"
- git config --global user.name "Peter Willert"
- make build
- cd ../barcamperfurt.github.io
- git init .
- git remote add origin git@github.com:barcamperfurt/barcamperfurt.github.io.git
- git add .
- git commit -nm \"Deployment\"
- git push origin master --force
- git config -l
- make deploy
env:
  global:
  - secure: K1dEw0fuCv8dNXdS7jefKWjHsnrMqUh760L0osGbOgyVBP+hjsbX83H3nloCbAsLx/HKperh5pHevWLgDNTjiuevvnmKLtcdLs6lVOMLEV4EIYn2fkfy93WBCozfhbzEKkdpb2IbccPQgGuURn0mzI5cLxQBYwbDNtyvBG82eLAGFRVL7kdntOFDrM9r7DsCWyDlirpe0ZCAdh2WqJwI6NpMQbmY6NV37xtM6+4F00QevED1lkBfhc4z9kQLq/ifT4s4fdOcxnhEDVw89ZG1fsDoDouSCQ/6UIB8FwuNzVFfwDySUql8CXd0hkaibelIP7ZXGubIyXYUjKGFoqke57XmmSsoQGgChEg7l2+GwUE5sNQALyhFTg4tpVj+z+7zK0LF0ajR5Tiu1b0wx4Nc08qYcsjUHK2l1C4X9tuaeQbQPuQtgcyOhyTCgCAKWxY32OYBSZXduL54aEgPEaOzpwXSRAIIOjmu1eW5WL6lg0mFbrV6Gs9hulvicFo7FuRcjliSxTxI5MbOXoTrR5/JO5RMMhT/XwhzDj+kU423ZU0Mb4CjGDdMbqNB2nqjQXfeJ7yd6ajadYYApeDsF8GGtK1pvPt2FqSBpab5Sx3Z/jZqIcpDYui2t3I55yBteWzMeZkjvM0Xr4n3o/gLXITy4Izz3sYedd+CWbD6Hu6x6T0=
